<div class="row-fluid">
    <div class="span6">
        <a href="/solicitacoes/novo" class="btn btn-success"><i class="icon-tags icon-2x"></i> <br> Nova Solicitação</a>
        <a href="/equipamentos/novo" class="btn btn-success"><i class="icon-briefcase icon-2x"></i> <br> Novo Equipamento</a>
        <a href="#printAgenda" class="btn" data-toggle="modal"><i class="icon-print icon-2x"></i> <br> Imprimir Agenda</a>
    </div>
</div>

<hr/>
