
<!DOCTYPE html>
<html lang="en" ng-app="psicontrole">
    <head>
        <meta charset="utf-8">
        <title>SSI - Vicentinos</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width, initial-scale=1.0">
        <!-- Le styles -->
        <link href="/css/login.css" media="screen" rel="stylesheet" type="text/css">

        <script type="text/javascript" src="/js/modernizr.min.js"></script>
        <!--[if lt IE 9]><script type="text/javascript" src="/js/html5.js"></script><![endif]-->
    </head>
    <body>
        <div class="login-header">
            <div class="logo txtCenter">
                <a href="/"><img src="/img/logo_login.png" alt="" style="width: 300px;"></a>
                <h3>Solicitações de Serviço de Informática</h3>
            </div>
        </div>
        <div class="container">
            <div class="login">
                <div class="row-fluid">
                    <div class="span12">
                        <div class="row-fluid">
                            <div class="span4 offset4">

                                <?php echo $this->messagem; ?>

                                <form method="post" name="auth" id="auth">
                                    <div class="control-group">
                                        <label class="control-label" for="inputEmail"><label for="email">E-mail</label></label>
                                        <div class="controls">
                                            <input type="email" name="email" class="input-xlarge" placeholder="Digite seu e-mail" value="" required="true">        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="inputPassword"><label for="senha">Senha</label></label>
                                        <div class="controls">
                                            <input name="senha" class="input-xlarge" type="password" value="" required="true">        </div>
                                    </div>
                                    <div class="control-group">
                                        <div class="controls">
                                            <input type="submit" name="submit" class="btn btn-success" value="Login">          
                                            <a href="/auth/request-password" class="btn btn-link">Esqueci minha senha</a>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="txtCenter">
                <hr>
                &copy; 2013 - Todos os direitos reservados - vicentinos.com.br <br><br>
            </footer>
        </div> <!-- /container -->
    </body>
</html>
