
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>SSI - vicentinos</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width, initial-scale=1.0">
        <!-- Le styles -->
        <link href="/css/login.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="login-header">
            <div class="logo txtCenter">
                <a href="/"><img src="/img/logo_login.png" alt="" style="width: 300px;"></a>
                <h3>Solicitações de Serviço de Informática</h3>
            </div>
        </div>
        <div class="container">
            <div class="login">
                <div class="row-fluid">
                    <div class="span12">
                        <h2>Esqueci minha senha</h2>

                        <hr>

                        <form method="post" name="auth" id="auth">
                            <p>Enviaremos em seu e-mail um link para que seja gerada uma nova senha. Nós não lhe enviaremos a senha atual devido a criptografia utilizada para o armazenamento das senhas.</p>
                            <br>

                            <div class="control-group">
                                <label class="control-label" for="inputEmail"><label for="email">E-mail</label></label>
                                <div class="controls">
                                    <input type="email" required="true" name="email" class="input-xlarge" placeholder="Digite seu e-mail" value="">    </div>
                            </div>
                            <div class="control-group">
                                <div class="controls">
                                    <input type="submit" name="submit" class="btn btn-primary" value="Enviar senha">    
                                    <a href="/" class="btn">Voltar para o Login</a>    
                                </div>
                            </div>

                        </form>                
                    </div>
                </div>
            </div>

            <footer class="txtCenter">
                <hr>
                &copy; 2013 - Todos os direitos reservados - vicentinos.com.br <br><br>
            </footer>
        </div> <!-- /container -->
    </body>
</html>
