<div>

    <div class="row-fluid">
        <div class="span6">
            <h2>Solicitação #<?php echo str_pad($this->ssi->id, 6, '0', STR_PAD_LEFT); ?></h2>
        </div>
    </div>

    <hr>

    <div class="row-fluid">
        <div class="span3 well">

            <div id="dadosSolicitacao">
                <h4>Informações</h4>

                <p><strong>Tipo:</strong> <?php echo ($this->ssi->id_tipo == null ? 'Não Definido' :$this->ssi->findParentRow('TipoSsi')->nome); ?></p>
                <p><strong>Processo:</strong> <?php echo ($this->ssi->id_processo == null ? 'Não Definido' :$this->ssi->findParentRow('Processo')->nome); ?></p>
                <p><strong>Situação:</strong> <?php echo $this->ssi->status; ?></p>
                <p><strong>Previsão Conclusão:</strong> <?php echo ($this->ssi->previsaoEncerramento == null ? 'Não Definido' : date("d/m/Y", strtotime($this->ssi->previsaoEncerramento))); ?></p>

            </div>

            <hr/>

            <h4 id="toggleDadosSolicitante" style="cursor: pointer;">Dados do Solicitante</h4>

            <div id="solicitante" style="display: none;">
                <div class="media">
                    <span class="pull-left"><i class="icon-user"></i></span>
                    <div class="media-body">
                        <?php echo $this->solicitante->nome; ?>			  
                    </div>
                </div>

                <div class="media">
                    <span class="pull-left"><i class="icon-phone"></i></span>
                    <div class="media-body">
                        (44) 4444-4444			  
                    </div>
                </div>

                <div class="media">
                    <span class="pull-left"><i class="icon-envelope-alt"></i></span>
                    <div class="media-body">
                        <a href="mailto:<?php echo $this->solicitante->email; ?>"><?php echo $this->solicitante->email; ?></a>
                    </div>
                </div>

                <div class="media">
                    <span class="pull-left"><i class="icon-home"></i></span>
                    <div class="media-body">
                        Empresa: <?php echo $this->solicitante->findParentRow('Empresa')->nome; ?>
                        Departamento: <?php echo $this->solicitante->findParentRow('Departamento')->nome; ?>
                    </div>
                </div>
            </div>

            <hr>

            <h4>Ações</h4>

            <?php if ($this->solicitante->id == $this->sessionStorage->read()->id && $this->ssi->status != "CONCLUIDA" && $this->ssi->status != "CANCELADA") : ?>
                <p>
                    <a href="/solicitacoes/solicita-posicao/id/<?php echo $this->ssi->id; ?>)" id="solicitarPosicao" class="btn btn-small btn-primary actions">
                        <i class="icon-question"></i> &nbsp; Solicitar Posicionamento
                    </a>
                </p>
            <?php endif; ?>

            <?php if ($this->ssi->status == "PENDENTE" && $this->sessionStorage->read()->role != "usuario") : ?>
                <p>
                    <a href="javascript:void(0);" class="btn btn-small btn-primary actions" data-toggle="modal" data-target="#modalClassificar">
                        <i class="icon-tasks"></i> &nbsp; Classificar Solicitação
                    </a>
                </p>
            <?php endif; ?>

            <?php if (($this->ssi->status != "TERCEIROS" && $this->ssi->status == 'ANDAMENTO') && $this->sessionStorage->read()->role != "usuario") : ?>   
                <p>
                    <a href="javascript:void(0);" class="btn btn-small btn-primary actions" data-toggle="modal" data-target="#modal">
                        <i class="icon-resize-small"></i> &nbsp; Transferir Solicitação
                    </a>
                </p>
            <?php endif; ?>

            <?php if ($this->sessionStorage->read()->role != "usuario" && ($this->ssi->status == "ANDAMENTO" || $this->ssi->status == "TERCEIROS")) : ?>
                <p>
                    <a href="javascript:void(0);" class="btn btn-small btn-success actions" data-toggle="modal" data-target="#modalConcluir">
                        <i class="icon-ok"></i> &nbsp; Concluir Solicitação
                    </a>
                </p>
            <?php endif; ?>

            <?php if ($this->ssi->status != "CANCELADA" && $this->ssi->status != "CONCLUIDA") : ?>
                <p>
                    <a href="/solicitacoes/cancela-solicitacao/id/<?php echo $this->ssi->id; ?>)" id="cancelarSolicitacao" class="btn btn-small btn-danger actions">
                        <i class="icon-remove"></i> &nbsp; Cancelar Solicitação
                    </a>
                </p>
            <?php endif; ?>

            <?php if ($this->ssi->status == "CANCELADA") : ?>
                <p>
                    <a href="/solicitacoes/reabre/id/<?php echo $this->ssi->id; ?>" id="reabre" class="btn btn-small btn-info actions">
                        <i class="icon-check"></i> &nbsp; Reabrir Solicitação
                    </a>
                </p>
            <?php endif; ?>

            <hr />

        </div>
        <div class="span9">

            <div id="resumo">
                <h4 class="fLeft">Resumo</h4>
                <p>
                    <?php echo $this->ssi->resumo; ?>
                </p>
            </div>

            <hr/>

            <div id="descricao">
                <h4 class="fLeft">Descrição</h4>
                <?php echo nl2br($this->ssi->descricao); ?>
            </div>

            <hr/>

            <ul class="nav nav-tabs">
                <li class="active"><a href="#historico" data-toggle="tab"><i class="icon-file-alt"></i> Histórico</a></li>
                <li><a href="#anexos" data-toggle="tab"><i class="icon-file-alt"></i> Anexos</a></li>
            </ul>

            <div class="tab-content clearfix">
                <div class="tab-pane active" id="historico">
                    <div class="activities">

                        <?php foreach ($this->ssi->findDependentRowset('HistoricoSsi') as $atividade) : ?>

                            <div class="activity">
                                <div class="clearfix muted">
                                    <span class="fLeft"><small><?php echo $atividade->findParentRow('Usuario')->nome; ?></small></span>
                                    <span class="fRight"><small><?php echo date("d/m/Y H:i:s", strtotime($atividade->dataHora)); ?></small></span>
                                </div>
                                <div class="media">
                                    <span class="pull-left"><i class="icon-file-alt"></i></span>
                                    <div class="media-body">
                                        <?php echo $atividade->descricao; ?>
                                    </div>
                                </div>				
                            </div>

                            <hr/>

                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="tab-pane" id="anexos">
                    asdfasdfas
                </div>
            </div>			

        </div>
    </div>

    <!-- Modal Transferir Solicitação -->
    <div id="modal" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Transferir Solicitação</h3>
        </div>
        <form method="post" action="/solicitacoes/transferir" id="formTransferir">
            <div class="modal-body">

                <div class="row-fluid">
                    <div class="span2 txtCenter">
                        <i class="icon-resize-small icon-3x muted"></i>
                    </div>
                    <div class="span10">
                        <div class="control-group">
                            <div class="controls" style="margin-top:10px;">
                                <input type="text" name="terceiro" class="input-xlarge" placeholder="Terceiro" value="" />
                                <input type="hidden" name="id_ssi" value="<?php echo $this->ssi->id; ?>" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                <input type="submit" value ="transferir" class="btn btn-primary">
            </div>
        </form>
    </div>

    <!-- Modal Concluir -->
    <div id="modalConcluir" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modalConcluir" aria-hidden="true">&times;</button>
            <h3>Concluir Solicitação</h3>
        </div>
        <form method="post" action="/solicitacoes/concluir" id="formConcluir">
            <div class="modal-body">

                <div class="row-fluid">
                    <div class="span2 txtCenter">
                        <i class="icon-check icon-3x muted"></i>
                    </div>
                    <div class="span10">
                        <div class="control-group">
                            <div class="controls" style="margin-top:10px;">
                                <textarea class="input-xlarge" name="descricao" rows="5" placeholder="Descrição"></textarea>
                                <input type="hidden" name="id_ssi" value="<?php echo $this->ssi->id; ?>" />
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                <input type="submit" value="Concluir" class="btn btn-primary">
            </div>
        </form>
    </div>

    <!-- Modal Classificar -->
    <div id="modalClassificar" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modalConcluir" aria-hidden="true">&times;</button>
            <h3>Classificar Solicitação</h3>
        </div>
        <form method="post" action="/solicitacoes/classificar" id="formClassificar">
            <div class="modal-body">

                <div class="row-fluid">
                    <div class="span2 txtCenter">
                        <i class="icon-tasks icon-3x muted"></i>
                    </div>
                    <div class="span10">
                        <div class="controls-row">

                            <div class="control-group label-inline">
                                <label for="tipo" class="control-label">Tipo de Solicitação:</label>
                                <div class="controls">
                                    <select name="tipo" id="tipo">
                                        <option value="">Todos</option>
                                    </select>
                                </div>                
                            </div>

                            <div class="control-group label-inline">
                                <label for="processo" class="control-label">Processo:</label>
                                <div class="controls">
                                    <select name="processo" id="processo">
                                        <option value="">todos</option>
                                    </select>
                                </div>                
                            </div>
                        </div>
                        <input type="hidden" name="id_ssi" value="<?php echo $this->ssi->id; ?>"
                               <div class="controls-row">

                            <div class="control-group label-inline">
                                <label for="previsaoConclusao" class="control-label">Previsão de Conclusão:</label>
                                <div class="controls">
                                    <input type="text" id="previsaoConclusao" name="previsaoConclusao" class="input-small datepicker"/>
                                </div>                
                            </div>

                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <a href="#." class="btn" data-dismiss="modal">Cancelar</a>
                    <input type="submit" value="Classificar" class="btn btn-primary">
                </div>
        </form>
    </div>


    <script type="text/javascript">

        $("#toggleDadosSolicitante").click(function() {
            $("#solicitante").toggle('slow');
        });

        $(function() {
            $("#cancelarSolicitacao").click(function(e) {
                e.preventDefault();
                var url = $(this).attr('href');
                var answer = confirm("Confirma o Cancelamento da Solicitação?");
                if (answer) {
                    window.location = url;
                } else {
                    return false;
                }
            });
        });

        $.getJSON('/ajax/get-tipo', {ajax: 'true'}, function(j) {
            var options = '<option value="">Selecione um tipo de Solicitação</option>';
            for (var i = 0; i < j.length; i++) {
                options += '<option value="' + j[i].id + '">' + j[i].nome + '</option>';
            }
            $('#tipo').html(options).show();
        });

        $.getJSON('/ajax/get-processos', {ajax: 'true'}, function(j) {
            var options = '<option value="">Selecione um Processo</option>';
            for (var i = 0; i < j.length; i++) {
                options += '<option value="' + j[i].id + '">' + j[i].nome + '</option>';
            }
            $('#processo').html(options).show();
        });

        $('#formTransferir').validate({
            rules: {
                terceiro: {required: true}
            }
        });

        $('#formConcluir').validate({
            rules: {
                descricao: {required: true}
            }
        });

        $('#formClassificar').validate({
            rules: {
                tipo: {required: true},
                processo: {required: true},
                previsaoConclusao: {required: true}
            }
        });

    </script>

</div>