<div class="row-fluid">
    <div class="span12">
        <h2><i class="icon-tags"></i> Solicitações de Serviço</h2>

        <hr>

        <p><a href="/tipos-ssi/novo" class="btn btn-primary"><i class="icon-tags"></i> &nbsp; Nova Solicitação</a></p>

        <div id="filtros" class="row-fluid" style="display: none;">

            <form method="post" class="well">
                <legend>Pesquisa de solicitações</legend>

                <div class="controls-row">
                    <div class="control-group">
                        <label for="texto" class="control-label">Texto dentro da solicitação:</label>
                        <div class="controls">
                            <input type="text" id="texto" name="texto" class="input-xlarge"/>
                        </div>                
                    </div>

                    &nbsp;&nbsp;

                    <div class="control-group">
                        <label for="texto" class="control-label">Situação da Solicitação: </label>
                        <div class="controls">
                            <label class="checkbox inline">
                                <input type="checkbox" id="inlineCheckbox1" value="option1"> Pendente
                            </label>
                            <label class="checkbox inline">
                                <input type="checkbox" id="inlineCheckbox2" value="option2"> Paralisada
                            </label>
                            <label class="checkbox inline">
                                <input type="checkbox" id="inlineCheckbox3" value="option3"> Aguardando Recursos
                            </label>
                            <label class="checkbox inline">
                                <input type="checkbox" id="inlineCheckbox3" value="option3"> Concluída
                            </label> 
                        </div>
                    </div>
                </div>

                <div class="controls-row">
                    <div class="control-group">
                        <label for="texto" class="control-label">Empresa:</label>
                        <div class="controls">
                            <select name="empresa">
                                <option value="">Todas</option>
                            </select>
                        </div>                
                    </div>
                </div>
            </form>
        </div>

        <div style="float: right;">
            <a href="javascrit:void(0);" id="toggleSearch" class="btn btn-primary btn-mini"><i class="icon-search"></i> Mostrar pesquisa</a>
        </div>

        <table class="table table-hover dataTable">
            <thead>
                <tr>
                    <th width="5%">#id</th>
                    <th>Nome</th>
                    <th width="10%">Situação</th>
                    <th width="10%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
        <script type="text/javascript">
            $(function() {
                var oTable = $('.dataTable').dataTable({
                    "bPaginate": false,
                    "bFilter": false,
                    "bInfo": false,
                    "oLanguage": {
                        "sProcessing": "Processando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "Não foram encontrados resultados",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": ""
                    }
                });

                $("#toggleSearch").click(function() {
                    $("#filtros").toggle('slow');
                });
            });
        </script> 
    </div>
</div>