<!DOCTYPE html>
<html>
    <head>
        <title>SSI vicentinos</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Bootstrap -->
        <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/lib/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">

        <!-- font-awesome -->
        <link rel="stylesheet" href="/lib/font-awesome/css/font-awesome.min.css">

        <!-- Application -->
        <link href="/css/app.css" rel="stylesheet" media="screen">

        <!-- scripts -->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="/js/jquery.dataTables.min.js"></script>
    </head>
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><img src="/img/logo.png" alt="" style="width: 150px;"/></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>
                                <a href="/">
                                    <i class="icon-dashboard"></i> 
                                    <br> Visão Geral                             
                                </a>
                            </li>

                            <li>
                                <a href="/cliente">
                                    <i class="icon-tags"></i> 
                                    <br> Solicitações de Serviço
                                </a>
                            </li>

                            <li>
                                <a href="/tratamento">
                                    <i class="icon-briefcase"></i> 
                                    <br> Tratamentos
                                </a>
                            </li>
                        </ul>
                        <ul class="nav pull-right">
                            <li><a href="/configuracoes"><i class="icon-cog"></i> <br> Configurações</a></li>
                            <!-- <li><a href="https://walbatroz.zendesk.com/categories/20127118-PsiControle" target="_blank"><i class="icon-question-sign"></i> <br> Ajuda</a></li> -->
                            <li class="divider-vertical"></li>
                            <li><a href="/auth/logout"><i class="icon-signout"></i> <br> Sair</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div style="margin-top: 100px;" class="visible-desktop"></div>

        <div class="container">

            <?php echo $this->layout()->content; ?>


            <br/>
            <footer>
                <hr>
                © SSI - Vicentinos do Brasil
            </footer>
        </div>
    </body>
</html>