<div class="row-fluid">
    <h2>Editar Empresa</h2>

    <hr>

    <form method="post" class="form-horizontal" id="empresa">
        <div class="row-fluid">
            <div class="span1 txtCenter">
                <i class="icon-building icon-3x muted"></i>
            </div>
            <div class="span11">
                <div class="control-group">
                    <label class="control-label">
                        <label for="nome">Nome Completo</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="nome" class="input-xxlarge" value="<?php echo $this->empresa->nome; ?>">							
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">
                        <label class="radio" for="situacao">Situação</label>
                    </label>
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="ativo" value="1" <?php echo ($this->empresa->ativo == 1 ? 'checked="checked"' : ''); ?> >Ativo
                        </label>
                        <label class="radio">
                            <input type="radio" name="ativo" value="0" <?php echo ($this->empresa->ativo == 0 ? 'checked="checked"' : ''); ?> >Inativo
                        </label>							
                    </div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Salvar">  
            <a href="/empresas" class="btn">Cancelar</a>
        </div>

    </form>
    
    <script type="text/javascript">
        $('#empresa').validate({
            rules: {
                nome: {required: true}
            }
        });
    </script>

</div>
