<div class="row-fluid">
    <div class="span12">
        <h2><i class="icon-building"></i> Empresas</h2>

        <hr>

        <p><a href="/empresas/novo" class="btn btn-primary"><i class="icon-building"></i> &nbsp; Nova Empresa</a></p>

        <table class="table table-hover dataTable">
            <thead>
                <tr>
                    <th width="5%">#id</th>
                    <th>Nome</th>
                    <th width="10%">Situação</th>
                    <th width="15%">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->empresas as $empresa) : ?>
                    <tr>
                        <td><?php echo $empresa->id; ?></td>
                        <td><a href="/empresas/editar/id/<?php echo $empresa->id; ?>"><?php echo $empresa->nome; ?></a></td>
                        <td><?php echo ($empresa->ativo == 1 ? 'Ativo' : 'Inativo'); ?></td>
                        <td>
                            <a href="/empresas/editar/id/<?php echo $empresa->id; ?>" class="btn btn-small"><i class="icon-edit"></i></a>
                            <a href="/empresas/departamentos/empresa/<?php echo $empresa->id; ?>" class="btn btn-success btn-small" title="Departamentos"><i class="icon-building"></i></a>
                            <a href="/empresas/remover/id/<?php echo $empresa->id; ?>" class="btn btn-danger btn-small delete"><i class="icon-remove-sign"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            $(function() {
                var oTable = $('.dataTable').dataTable({
                    "sPaginationType": "full_numbers",
                    "sDom": 'f<"toolbar">lrtip',
                    "oLanguage": {
                        "sProcessing": "Processando...",
                        "sLengthMenu": "Mostrar _MENU_ registros",
                        "sZeroRecords": "Não foram encontrados resultados",
                        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                        "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                        "sInfoFiltered": "(filtrado de _MAX_ registros no total)",
                        "sInfoPostFix": "",
                        "sSearch": "Buscar:",
                        "sUrl": "",
                        "oPaginate": {
                            "sFirst": "Primeiro",
                            "sPrevious": "Anterior",
                            "sNext": "Seguinte",
                            "sLast": "Último"
                        }
                    }
                });
                var select = '<select name="situacao">';
                select += '<option value="">Todos</option>';
                select += '<option value="Ativo">Ativos</option>';
                select += '<option value="Inativo">Inativos</option>';
                select += '</select>';
                $("div.toolbar").html('<label>Filtrar: ' + select + '</label>');
                $('select[name=situacao]', this).change(function() {
                    oTable.fnFilter($(this).val(), 2);
                });
            });
        </script> 
    </div>
</div>