<div class="row-fluid">
    <h2>Nova Empresa</h2>

    <hr>

    <form method="post" class="form-horizontal" id="empresa">
        <div class="row-fluid">
            <div class="span1 txtCenter">
                <i class="icon-building icon-3x muted"></i>
            </div>
            <div class="span11">
                <div class="control-group">
                    <label class="control-label">
                        <label for="nome">Nome Completo</label>
                    </label>
                    <div class="controls">
                        <input type="text" name="nome" class="input-xxlarge">							
                    </div>
                </div>
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" id="submitbutton" class="btn btn-primary" value="Salvar">  
            <a href="/empresas" class="btn">Cancelar</a>
        </div>

    </form>

    <script type="text/javascript">
        $('#empresa').validate({
            rules: {
                nome: {required: true, minLenght: 2}
            }
        });
    </script>

</div>
