<div class="hero">
    <div class="container" style="text-align: center;">
        <h1 class="hero-text animated fadeInDown">Desculpe... você não possui permissão para visualizar isso :(</h1>
        <br/>
        <p class="sub-text animated fadeInDown">
            Você não possui os privilégios necessários para acessar essa página. Você pode entrar em contato com seu supervisor ou equipe de TI
            e solicitar.
        </p>
        <br/>
        <div class="cta animated fadeInDown">
            <a href="javascript:history.go(-1)" class="btn btn-success">Voltar de onde vim</a>
            <a href="signup.html" class="btn btn-primary">Informar erro</a>
        </div>
    </div>		
</div>