<div class="hero">
    <div class="container" style="text-align: center;">
        <h1 class="hero-text animated fadeInDown">Ops... Página não encontrada :(</h1>
        <br/>
        <p class="sub-text animated fadeInDown">
            Desculpe, a página que você está tentando acessar não existe.
        </p>
        <br/>
        <div class="cta animated fadeInDown">
            <a href="javascript:history.go(-1)" class="btn btn-success">Voltar de onde vim</a>
            <a href="signup.html" class="btn btn-primary">Informar erro</a>
        </div>
    </div>		
</div>